version: '3.8'

services:
  sipayu-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sipayu-app:latest
    container_name: sipayu-app
    ports:
      - "9091:80"
    environment:
      - APP_ENV=production
    volumes:
      - .:/var/www/html
      - sipayu_vendor:/var/www/html/vendor
    restart: unless-stopped
    command: ["frankenphp", "run", "-c", "caddy/Caddyfile"]

volumes:
  sipayu_vendor: