version: '3'
services:
  esmk:
    environment:
      CONTAINER_ROLE: app
    image: sipayu
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    working_dir: /var/www
    volumes:
      - app_storage:/var/www/storage/app

volumes:
  app_storage:


# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: lumen-app
#     working_dir: /var/www/html
#     volumes:
#       - .:/var/www/html
#     networks:
#       - lumen-network
#     ports:
#       - "8000:8000"

  # nginx:
  #   image: nginx:alpine
  #   container_name: lumen-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - .:/var/www/html
  #   networks:
  #     - lumen-network
  #   depends_on:
  #     - app

# networks:
#   lumen-network:
#     driver: bridge
