version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80" # Expose port 80 untuk akses aplikasi
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      - DB_HOST=27.112.78.145
      - DB_PORT=5432
      - DB_DATABASE=sipayu_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=k3s24fGWWQ6FKZnRWDbAaBhiYWB6jxIZLtRNAYGwW4Ea8GepKXyBWQqDRBwpwrea
      - JWT_SECRET=YPlJAj6L74PHwVZQDucBulT77xTb53wGTjysOI1YsReyD59SiMxXlFl6BlKYlHgD
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_USERNAME=disparaindramayu@gmail.com
      - MAIL_PASSWORD=vrfomwvazgcgcwlz
      - MAIL_ENCRYPTION=ssl
      - MAIL_FROM_ADDRESS=disparaindramayu@gmail.com
      - MAIL_FROM_NAME=SIPAYU
    networks:
      - lumen-network

networks:
  lumen-network: