services:
  web:
    build: .
    tty: true
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./letsencrypt:/etc/letsencrypt # Volume untuk menyimpan sertifikat
      - ./ssl:/etc/ssl # Volume untuk menyimpan file SSL
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - APP_URL=http://sipayu.gincumediatek.com
      - DB_CONNECTION=pgsql
      - DB_HOST=27.112.78.145
      - DB_PORT=5432
      - DB_DATABASE=sipayu_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=k3s24fGWWQ6FKZnRWDbAaBhiYWB6jxIZLtRNAYGwW4Ea8GepKXyBWQqDRBwpwrea
      - JWT_SECRET=YPlJAj6L74PHwVZQDucBulT77xTb53wGTjysOI1YsReyD59SiMxXlFl6BlKYlHgD
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=disparaindramayu@gmail.com
      - MAIL_PASSWORD=vrfomwvazgcgcwlz
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=disparaindramayu@gmail.com
      - MAIL_FROM_NAME=SIPAYU
      - QUEUE_CONNECTION=sync
      - MINIO_KEY=2gzpw0kJr2ET4idkZjqD
      - MINIO_SECRET=gpqPNHeHQ2X8fjIMKFRfO50HUiwLZUrHsAwXmhti
      - MINIO_REGION=us-east-1
      - MINIO_ENDPOINT=https://minio-storage-sipayu.gincumediatek.com
      - MINIO_BUCKET=sipayu-production
      - MINIO_VERSION=latest
      - REDIS_CLIENT=predis
      - REDIS_HOST=27.112.78.145
      - REDIS_PASSWORD=ssOTa8RdP9RMQ2R74sfCFysBsELtSAFrr4oegHc2TQHgTxvxF7ql2GjXlKApgy2T
      - REDIS_PORT=6389
      - REDIS_DATABASE=0
      - REDIS_CACHE_DATABASE=1
      - CACHE_REDIS_CONNECTION=default
      - CACHE_DRIVER=redis
    networks:
      - lumen-network

networks:
  lumen-network: