services:
  web:
    build: .
    tty: true
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./letsencrypt:/etc/letsencrypt # Volume untuk menyimpan sertifikat
      - ./ssl:/etc/ssl # Volume untuk menyimpan file SSL
    environment:
      - APP_NAME=SIPAYU
      - APP_ENV=production
      - APP_KEY=HVp7Jrar9PKHH7HQgMrVh3pAOAV2qKd0
      - APP_DEBUG=true
      - APP_URL=https://apps.sipayu.info
      - APP_TIMEZONE=UTC
      - LOG_CHANNEL=stack
      - LOG_SLACK_WEBHOOK_URL=
      - DB_CONNECTION=pgsql
      - DB_HOST=103.172.70.65
      - DB_PORT=5432
      - DB_DATABASE=sipayu_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=q8SwHPT3VZNCLTmXZ3XOszHxsWPVmOaUehhVqaXxJIgPQXRoFRnVqWKWeHJEu5ng
      - QUEUE_CONNECTION=sync
      - JWT_SECRET=YPlJAj6L74PHwVZQDucBulT77xTb53wGTjysOI1YsReyD59SiMxXlFl6BlKYlHgD
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=disparaindramayu@gmail.com
      - MAIL_PASSWORD=vrfomwvazgcgcwlz
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=disparaindramayu@gmail.com
      - MAIL_FROM_NAME="${APP_NAME}"
      - MINIO_KEY=pSfATwhfHdKUfyRhN3uU
      - MINIO_SECRET=BCFkYnqMnyVxszoxw9ylLIrnJEphrTNA3R2qspg1
      - MINIO_REGION=us-east-1
      - MINIO_ENDPOINT=https://s3.sipayu.info
      - MINIO_BUCKET=sipayu-production
      - MINIO_VERSION=latest
      - REDIS_CLIENT=predis
      - REDIS_HOST=103.172.70.65
      - REDIS_PASSWORD=vmqvK9abZH3opwoMJqCReH3jWJRKPyWlLtKys70eUEkfPTtkCmCkqCU8zztFDvvM
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
      - REDIS_CACHE_DATABASE=1
      - CACHE_REDIS_CONNECTION=default
      - CACHE_DRIVER=redis
    networks:
      - lumen-network

networks:
  lumen-network: