version: '3.8'

services:
  app:
    build: .
    image: sipayu-api-lumen-app
    container_name: lumen_app
    restart: unless-stopped
    expose:
      - "8000"  # Hanya expose port 8000 di jaringan internal Docker
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"   # HTTP
      # - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount konfigurasi Nginx
      # - ./ssl:/etc/nginx/ssl  # Folder untuk sertifikat SSL (jika menggunakan HTTPS)
    depends_on:
      - app