version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      - DB_HOST=27.112.78.145
      - DB_PORT=5432
      - DB_DATABASE=sipayu_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=k3s24fGWWQ6FKZnRWDbAaBhiYWB6jxIZLtRNAYGwW4Ea8GepKXyBWQqDRBwpwrea
      - JWT_SECRET=YPlJAj6L74PHwVZQDucBulT77xTb53wGTjysOI1YsReyD59SiMxXlFl6BlKYlHgD

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.pem:/etc/ssl/certs/cert.pem
      - ./ssl/key.pem:/etc/ssl/private/key.pem
    depends_on:
      - app